name: Test

on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: rwthika/tensorflow-cc:latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -la
